### ISSUE TITLE
Executable will not run on Windows 10

### ISSUE THREAD

**Issue by walshal** [analogdevicesinc/iio-oscilloscope#153]
I installed the version 0.10 windows executable on Windows 10. When i try to run iio-scope i get the following message
![image](https://user-images.githubusercontent.com/49532146/55978538-001b9680-5c5e-11e9-952a-08368b2143fd.png)

**Comment by rgetz** [comment]
I don't get this error - I just tried it. 

Are you on Win32, or Win64?

**Comment by walshal** [comment]
Win64. I noticed I only get this error when my laptop is plugged into dual external monitors. If I open iioscope on the laptop monitor it opens correctly. Seems to be linked to display settings.

**Comment by mhennerich** [comment]
Can you try to delete following file?

C:\Users\YOUR-USER\AppData\Local\.osc_profile.ini

OSC saves the last position of the window and if that position doesn't exist (because it's currently outside the available desktop area) undesired behavior might exist. We have a look and fix this soon.

-Michael

**Comment by mhennerich** [comment]
@adisuciu can someone have a look?

**Comment by walshal** [comment]
I couldn't find that file in the location you stated. I did find it in c:\tmp but deleting it didn't help. Iioscope would not open when monitors plugged in.

**Comment by adisuciu** [comment]
2e5ca7448129f4b0cf5c39a65b5b9b5dfde24674 should fix it

**Comment by mhennerich** [comment]
closed
